# Numpy 套件

In [4]:
a =[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [6]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype)  #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [7]:
print(np.zeros(6)) # 產生六個元素均為0的一維array
print(np.zeros((3,6))) # 產生18個元素均為0的二維array
print(np.zeros((2,3,6))) # 產生36個元素均為0的三維array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [8]:
a = np.zeros(16)
print(a)
print(a.shape)
b =a.reshape((4,4)) #改變資料維度為4x4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


## ndarray 的進階操作

In [9]:
print(np.arange(11)) #產生一個0-10的一維陣列

[ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])    #取0,1,2,3,4位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [11]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b = np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c = np.array(np.arange(0,10).reshape(2,5))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## 二維ndarray 取值

In [17]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:]) #第0列的元素
print(my_2d_array[1,]) #第1列的元素
print(my_2d_array[:,0])  #第0列的元素                     
print(my_2d_array[1,1])  #第2列第0欄的元素                    

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


## 假設有六個組別"Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"
## 其參加人數分別為56,8,19,16,6,71人

In [24]:
import numpy as np
groups =["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman=[56, 8, 19, 16, 6, 71]
groups_array =np.array(groups)
ironman_array =np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 16  6 71]


## 請問大於10的組別有哪些?

In [27]:
# 用人數區篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']


## 除了自我挑戰組之外的組別,人數為何?

In [28]:
# 用組別區篩選組別
print(groups_array != "自我篩選組")
print(ironman_array[groups_array !="自我挑戰組"])

[ True  True  True  True  True  True]
[56  8 19 16  6]


## ndarray 空值 nan 無限大 inf

In [30]:
nan_array = np.array([56, 8,19,14, 6, np.nan]) ##nan是空值的意思
print(nan_array)

[56.  8. 19. 14.  6. nan]


## 生成10組標準常態分配(平均為0，標準差為1的常態分配)隨機變數

In [32]:
normal_samples =np.random.normal(size=10)
print(normal_samples)

[ 2.20739529  0.12774593 -1.04937123 -1.2109825   1.78006366  0.32586242
 -1.87043169  1.79218479  0.34639184  0.73807366]


## 生成10組介於0~15之間的隨機變數

In [31]:
uniform_samples =np.random.uniform(size=10)
print(uniform_samples)

[0.79382065 0.42402918 0.36695907 0.61823055 0.33108964 0.77713811
 0.73330707 0.68294765 0.76154529 0.56937978]
